### ISSUE TITLE
try to use it but got error

### ISSUE THREAD

**Issue by budarin** [slok/alertgram#27]
docker-compose.yml

```
    alertgram:
        image: slok/alertgram
        ports:
            - 8080:8080
            - 8081:8081
        environment:
            - telegram.api-token=XXXXXX
            - telegram.chat-id=YYYYYYY
```
 error:
`error running the app: telegram api token is required`

where
`XXXXXX` - real API token
`YYYYYYY` - real chat id
