### ISSUE TITLE
Have alerts in alertmanager but none in telegramm channel :(

### ISSUE THREAD

**Issue by budarin** [slok/alertgram#29]
Created channel and add created bot in to channel admins 

got alerts in alertmanager but nothing got in telegramm

docker-compose.yml
```
    alertgram:
        image: slok/alertgram
        ports:
            - 8080:8080
            - 8081:8081
        environment:
            - ALERTGRAM_TELEGRAM_API_TOKEN=<token>
            - ALERTGRAM_TELEGRAM_CHAT_ID=<channel ID>
```

alermanager.yml
```
receivers:
    - name: 'telegram'
      webhook_config:
          - url: 'http://alertgram:8080/alerts'
```

have tried to call
`curl -i http://localhost:8080/alerts -d @./docker/base.json`

`base.json` is from you repository

got response
```
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Date: Sat, 14 Nov 2020 02:43:19 GMT
Content-Length: 0
```

but nothing in channel
