### ISSUE TITLE
Multiple telegram chat

### ISSUE THREAD

**Issue by Shm013** [slok/alertgram#30]
I want to send alerts into two different chat?
How can I do this?
Is multiple `telegram.chat-id` options supported?

**Comment by Shm013** [comment]
I Done this in alertmanager level
```
receivers:
- name: telegram
    webhook_configs:
    - url: 'http://alertgram:8080/alerts'
      send_resolved: false
    - url: 'http://alertgram:8080/alerts?chat-id=-1001111111111'
      send_resolved: false
```
